# Generated by Django 4.2.2 on 2024-09-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ver_code",
            field=models.CharField(
                default="499451428460", max_length=15, verbose_name="код из письма"
            ),
        ),
    ]
