# Generated by Django 4.2.2 on 2024-09-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_ver_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ver_code",
            field=models.CharField(
                default="059311025520", max_length=15, verbose_name="код из письма"
            ),
        ),
    ]
