# Generated by Django 4.2.2 on 2024-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_ver_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ver_code",
            field=models.CharField(
                default="247288799997", max_length=15, verbose_name="код из письма"
            ),
        ),
    ]
