# Generated by Django 4.2.2 on 2024-09-18 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="электронная почта"
                    ),
                ),
                ("fio", models.CharField(max_length=100, verbose_name="ФИО")),
                ("comment", models.TextField(verbose_name="комментарий")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="тема письма")),
                ("body", models.TextField(verbose_name="тело письма")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("running", "запущена"),
                            ("completed", "завершена"),
                        ],
                        default="created",
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                (
                    "time_start",
                    models.TimeField(
                        help_text="Введите время в формате ЧЧ:ММ через двоеточие. Начало времени отправки быть раньше окончания времени отправки ",
                        verbose_name="начало времени отправки",
                    ),
                ),
                (
                    "time_end",
                    models.TimeField(
                        help_text="Введите время в формате ЧЧ:ММ через  двоеточие. Начало времени отправки быть раньше окончания времени отправки ",
                        verbose_name="окончание времени отправки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("day", "раз в день"),
                            ("week", "раз в неделю"),
                            ("mon", "раз в месяц"),
                        ],
                        max_length=20,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        blank=True,
                        help_text="Введите число при периодичности раз в месяц. Число должно быть от 1 до 31",
                        null=True,
                        verbose_name="день",
                    ),
                ),
                (
                    "day_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "понедельник"),
                            ("1", "вторник"),
                            ("2", "среда"),
                            ("3", "четверг"),
                            ("4", "пятница"),
                            ("5", "суббота"),
                            ("6", "вскресенье"),
                        ],
                        help_text="Выберите день недели при периодичности раз в неделю",
                        max_length=15,
                        null=True,
                        verbose_name="день недели",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="активность рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_try",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        verbose_name="дата и время попытки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Успешно"), ("0", "Неуспешно")],
                        max_length=20,
                        verbose_name="статус попытки",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ почтового сервера"
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="клиент"
                    ),
                ),
                (
                    "mailing_current",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
                "ordering": ["-time_try"],
            },
        ),
    ]
