# Generated by Django 4.2.2 on 2024-09-29 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_time_end_alter_mailing_time_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglog",
            name="time_try",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="дата и время попытки"
            ),
        ),
    ]
