# Generated by Django 4.2.2 on 2024-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailinglog_time_try"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglog",
            name="time_try",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата и время попытки"
            ),
        ),
    ]
